### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by riteshaws** [AAdewunmi/Java-Email-Application#2]
Getting this issue

javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at

**Comment by AAdewunmi** [comment]
Hi, 

Check out:

1. https://stackoverflow.com/questions/35347269/javax-mail-authenticationfailedexception-535-5-7-8-username-and-password-not-ac

2. https://www.youtube.com/watch?v=IWxwWFTlTUQ

😎
